import { contextBridge, ipcRenderer } from 'electron'
contextBridge.exposeInMainWorld('api', {
  fkCreate: (plan:string, locale:string) => ipcRenderer.invoke('FK_CREATE', { plan, locale }),
  getVersion: () => ipcRenderer.invoke('GET_VERSION'),
  getLocale: () => ipcRenderer.invoke('GET_LOCALE'),
  setLocale: (locale:'ru'|'en') => ipcRenderer.invoke('SET_LOCALE', locale),
  getPlatform: () => process.platform,
  getSettings: () => ipcRenderer.invoke('GET_SETTINGS'),
  setSettings: (patch:any) => ipcRenderer.invoke('SET_SETTINGS', patch),
  listShots: (limit?:number) => ipcRenderer.invoke('LIST_SHOTS', limit),
  openShotsDir: () => ipcRenderer.invoke('OPEN_SHOTS_DIR'),
  listTextHistory: (limit?:number) => ipcRenderer.invoke('LIST_TEXT_HISTORY', limit),
  openPath: (p:string) => ipcRenderer.invoke('OPEN_PATH', p),
  revealFile: (p:string) => ipcRenderer.invoke('REVEAL_FILE', p),
  openLogsDir: () => ipcRenderer.invoke('OPEN_LOGS_DIR'),
  exportLogsCopy: () => ipcRenderer.invoke('EXPORT_LOGS_COPY'),
  pickDir: () => ipcRenderer.invoke('PICK_DIR'),
  getUserDataDir: () => ipcRenderer.invoke('GET_USERDATA_DIR'),
  openUserDataDir: () => ipcRenderer.invoke('OPEN_USERDATA_DIR'),
   getDeviceMeta: () => ipcRenderer.invoke('GET_DEVICE_META'),
   deviceRegisterOnce: () => ipcRenderer.invoke('DEVICE_REGISTER_ONCE'),
   licenseValidate: () => ipcRenderer.invoke('LICENSE_VALIDATE'),
   pairCreate: () => ipcRenderer.invoke('PAIR_CREATE'),
   pairConsume: (code:string) => ipcRenderer.invoke('PAIR_CONSUME', code),
   getOrgStatus: () => ipcRenderer.invoke('GET_ORG_STATUS'),
   exportOrgKeysCsv: () => ipcRenderer.invoke('EXPORT_ORG_KEYS_CSV'),
  onResetUI: (cb:()=>void)=>{ try{ ipcRenderer.removeAllListeners('RESET_UI'); ipcRenderer.on('RESET_UI', ()=>cb&&cb()) }catch{} },
})
