openapi: 3.0.3
info:
  title: GetLifeUndo API
  version: 1.0.0
servers:
  - url: https://getlifeundo.com
paths:
  /api/healthz:
    get:
      summary: Health check
      responses:
        '200': { description: OK }
  /api/debug/fk:
    get:
      summary: FreeKassa debug flags
      responses:
        '200': { description: OK }
  /api/license/validate:
    get:
      summary: Validate a license key (stub endpoint)
      parameters:
        - in: query
          name: key
          schema: { type: string }
      responses:
        '200': { description: OK }