name: CI

on:
  push:
    branches: [ main, site/refresh-B, release/* ]
  pull_request:
    branches: [ main, site/refresh-B ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Test basic URLs
        run: |
          echo "Testing basic connectivity..."
          curl -I https://getlifeundo.com/ru || echo "Site check failed"
          echo "CI test completed"
