name: Lighthouse CI (getlifeundo.com)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches: [ main, site/refresh-B, release/* ]
jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://getlifeundo.com/ru
            https://getlifeundo.com/en
            https://getlifeundo.com/ru/features
            https://getlifeundo.com/en/downloads
          configPath: ./lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
