name: Update index.html with payment form
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Inject VIP payment form
        run: |
          set -eu
          FILE="public/index.html"
          mkdir -p public
          cat > "$FILE" <<'HTML'
<!doctype html><html lang="ru"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>GetLifeUndo — Оплата VIP</title>
</head><body>
<h1>VIP лицензия (Lifetime)</h1>
<form method="POST" action="/api/fk/create">
  <input type="hidden" name="plan" value="vip_life">
  <label>Email для ключа:<br><input name="email" type="email" required></label><br><br>
  <button type="submit">Оплатить через FreeKassa</button>
</form>
<p><a href="/success">После оплаты вы попадёте на эту страницу</a> • <a href="/fail">или эта при ошибке</a></p>
</body></html>
HTML
      - name: Commit & push
        run: |
          git config user.name "gh-actions"
          git config user.email "actions@github.com"
          git add public/index.html
          git commit -m "chore(ci): update public/index.html with VIP payment form [skip ci]" || echo "no changes"
          git push
